# Generated by Django 5.2.16 on 2026-10-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_customer_name_order_payment_method_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_image_url',
            field=models.URLField(blank=True),
        ),
    ]
