# Generated by Django 5.2.16 on 2026-10-03 19:56

from django.db import migrations, models


def mark_existing_card_orders_as_simulated(apps, schema_editor):
    Order = apps.get_model('store', 'Order')
    Order.objects.filter(payment_method='CARD').update(payment_status='SIMULATED')


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('SIMULATED', 'Simulated')], default='NOT_REQUIRED', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_checkout_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(
            mark_existing_card_orders_as_simulated,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on delivery'), ('CARD', 'Card (Stripe Checkout)')], default='COD', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting payment'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PROCESSING', max_length=20),
        ),
    ]
