# Generated by Django 5.2.16 on 2026-10-05 10:31

import django.core.validators
import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_carrier_order_delivered_at_order_shipped_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('BANNER', 'Banner'), ('TEXT', 'Text'), ('IMAGE', 'Image')], default='TEXT', max_length=10)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('button_label', models.CharField(blank=True, max_length=60)),
                ('button_url', models.CharField(blank=True, max_length=500, validators=[store.models.validate_content_link])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('seo_description', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PageContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page_placements', to='store.contentblock')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='store.contentpage')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='contentblock',
            name='pages',
            field=models.ManyToManyField(related_name='content_blocks', through='store.PageContentBlock', to='store.contentpage'),
        ),
        migrations.AddConstraint(
            model_name='pagecontentblock',
            constraint=models.UniqueConstraint(fields=('page', 'block'), name='unique_content_block_per_page'),
        ),
    ]
