# Generated by Django 5.2.16 on 2026-10-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_contentblock_contentpage_pagecontentblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_tracking_token_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Set a future time to schedule publication; leave blank to publish immediately.', null=True),
        ),
    ]
